spring.application.name=gateway-service
server.port=8050

# Eureka server configs
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true



spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


logging.level.org.springframework.cloud.gateway=trace
logging.level.org.springframework.http.server.reactive=debug



spring.cloud.gateway.routes[0].id=appointment-service
spring.cloud.gateway.routes[0].uri=http://localhost:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/appointments/**


# -------------------------------
# ROUTE 2 — Patient Service
# -------------------------------
spring.cloud.gateway.routes[1].id=patient-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/patients/**

# -------------------------------
# ROUTE 3 — Prescription Service
# -------------------------------
spring.cloud.gateway.routes[2].id=prescription-service
spring.cloud.gateway.routes[2].uri=http://localhost:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/prescriptions/**
#
## -------------------------------
## ROUTE 4 — Pharma Service
## -------------------------------
#spring.cloud.gateway.routes[3].id=pharma-service
#spring.cloud.gateway.routes[3].uri=lb://pharma-service
#spring.cloud.gateway.routes[3].predicates[0]=Path=/api/pharma/**
#
## -------------------------------
## ROUTE 5 — Billing Service
## -------------------------------
spring.cloud.gateway.routes[3].id=billing-service
spring.cloud.gateway.routes[3].uri=http://localhost:8086
spring.cloud.gateway.routes[3].predicates[0]=Path=/bills/**
#
## -------------------------------
## ROUTE 6 — Doctor Service
## -------------------------------
spring.cloud.gateway.routes[4].id=doctor-service
spring.cloud.gateway.routes[4].uri=http://localhost:8082
spring.cloud.gateway.routes[4].predicates[0]=Path=/doctors/**